markdown: kramdown
pygments: true
permalink: /posts/:title
auto: true
rdiscount:
  extensions: [smart]

paginate: 20

name: Zac Ioannidis
url: izac.us
description: How d'ya like them apples?
twitter: zacoppotamus
github: zacoppotamus
gravatar_url: http://www.gravatar.com/avatar/06c339b15e9be97f965016fc56eda6fa.png